/*
  PRATICAR CRIAÇÃO DE BANCOS DE DADOS E TABELAS COM CONSTRAINTS
  Professor: Wanderlei Silva do Carmo
*/

CREATE DATABASE IF NOT EXISTS BD_LOJA;
USE BD_LOJA;

CREATE TABLE IF NOT EXISTS LOJA(
  CODIGO INT NOT NULL AUTO_INCREMENT,
  LOCAL VARCHAR(50),
  PRIMARY KEY(CODIGO)  
);

CREATE TABLE IF NOT EXISTS VENDEDOR(
  CODIGO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  COD_LOJA INT ,
  PRIMARY KEY (CODIGO),
  CONSTRAINT FK_COD_VENDEDOR 
  FOREIGN KEY(COD_VENDEDOR) 
  REFERENCES LOJA(CODIGO) 
);

CREATE TABLE IF NOT EXISTS PRODUTO (
   CODIGO INT NOT NULL AUTO_INCREMENT,
   DESCRICAO VARCHAR(50) NOT NULL,
   UNIDADE VARCHAR(50),
   VALOR_UNITARIO DECIMAL(8,2),
   PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS VENDA(
   CODIGO INT NOT NULL AUTO_INCREMENT,
   DATA_HORA DATETIME NOT NULL,
   COD_PRODUTO INT NOT NULL,
   COD_LOJA INT NOT NULL, 
   COD_VENDEDOR INT NOT NULL,
   PRIMARY KEY(CODIGO),
   CONSTRAINT FK_PROD_COD_PRODUTO 
   FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(CODIGO),
   CONSTRAINT FK_LOJA_COD_LOJA 
   FOREIGN KEY(COD_LOJA) REFERENCES LOJA(CODIGO),
   CONSTRAINT FK_VENDEDOR_COD_VENDEDOR 
   FOREIGN KEY(COD_VENDEDOR) REFERENCES VENDEDOR(CODIGO)
);
