/*

    STORED PROCEDURE COM CURSOR USANDO ESTRUTURAS DE REPETIÇÃO WHILE
*/

USE db_loja;

DROP PROCEDURE IF EXISTS sp_listar_produtos;

DELIMITER $$
CREATE PROCEDURE sp_listar_produtos() 
BEGIN
DECLARE LISTA TEXT DEFAULT "";
DECLARE PRODUTO VARCHAR(50) DEFAULT "";
DECLARE VALOR_UNITARIO DECIMAL(8,2) DEFAULT 0.00;
DECLARE CONTADOR INTEGER DEFAULT 0;
DECLARE TOTAL INTEGER DEFAULT 0;

DECLARE C CURSOR FOR SELECT descricao, valor_unitario FROM PRODUTO;
DECLARE C2  CURSOR FOR SELECT count(*) FROM PRODUTO;

DROP TABLE IF EXISTS LISTA_PRODUTOS_TEMP;
CREATE TEMPORARY TABLE LISTA_PRODUTOS_TEMP (PRODUTO VARCHAR(50), VALOR_UNITARIO DECIMAL(8,2), UNIQUE(PRODUTO,VALOR_UNITARIO) );

OPEN C2;
  FETCH C2 INTO TOTAL;
CLOSE C2;

OPEN C;
SET CONTADOR = 0;
	WHILE   CONTADOR < TOTAL DO 
       FETCH C INTO PRODUTO,VALOR_UNITARIO;
       SET CONTADOR = CONTADOR + 1;
       -- SET VALOR_UNITARIO = "10.00";
       INSERT INTO LISTA_PRODUTOS_TEMP(PRODUTO,VALOR_UNITARIO) VALUES (PRODUTO,VALOR_UNITARIO);
    END WHILE;
CLOSE C;

/* 
  PARA IMPORTAR USARIAMOS O LOAD DATA INFILE  "C:/TEMP/LISTA_PRODUTOS_TEMP.CSV" INTO TABLE LISTA_PRODUTOS_TEMP";
  

--EXPORTANDO PARA O FORMATO CSV - PODE SER ABERTO PELO EXCEL.
-- SELECT * FROM LISTA_PRODUTOS_TEMP INTO OUTFILE  "C:/Users/Wanderlei/LISTA_PRODUTOS_TEMP.csv" 
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

*/

END $$
DELIMITER ;

CALL sp_listar_produtos;

